### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jkoritzinsky** [robotdotnet/robotdotnet.github.io#1]
We need to set up updated documentation as well as get a system set up for easily updating documentation. I'm unsure as to your current setup, and since the docs haven't been updated in months, I think it would be a good idea to update them soon.

**Comment by ThadHouse** [comment]
It was using sandcastle, but there was an issue with the way it was set up. It wouldn't grab any of the remarks or code comments, and would only grab the base XML. What it needs is its own sandcastle project, which downloads the solutions to both WPILib and NetworkTables and links to the solutions, and not the individual DLL's. Theres a start to a lot of this is the tools repository, but theres a lot that needs to be done. We also need a tool built into the extension to download mono and deploy it to the RoboRIO. The biggest issue with that currently is we need somewhere to host the mono package. Its about 30 MB, which is too large for github to do reasonably.

**Comment by jkoritzinsky** [comment]
I see. Looks like we've got a lot of work to get done before January.

BTW for the mono package we could use Git LFS.

**Comment by ThadHouse** [comment]
Looks like theres a 12 GB yearly bandwidth limit for that, which probably isnt that big of a deal. Do you know if its fast to download, and how to set it up?

**Comment by jkoritzinsky** [comment]
Its just a git extension.  [The website](https://git-lfs.github.com/) looks like it explains how to set it up pretty easily.

**Comment by ThadHouse** [comment]
If its not faster then the current github its not necessary. Standard git allows up to 50 MB files. Plus we would need to be able to grab it using standard HTTP, which adding it to the website currently allows.

**Comment by ThadHouse** [comment]
This has been done, so closing
